add ui unit test
autogluon/autogluon-assistant pull request #168
Opened 2024-12-06 23:55 UTC by tianyuanzoe

## Description

Adding unit test for Autogluon-Assistant UI

## How Has This Been Tested?

- [x] Unit tests (`pytest tests/`)
- [ ] Integration tests (if applicable)

## Configuration Changes

- [x] No config changes
- [ ] Config changes (please describe):

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Performance improvement
- [x] Code cleanup/refactor

2024-12-13 11:12 UTC, AnirudhDagar requested changes
@tianyuanzoe Two high level comments other than the import specific comments which are causing tests failures:

1. Please move the tests into the root tests dir under ui (you will need to create this directory): tests/unittests/ui/<test_name.py, ...>
2. [Not directly related to this PR] Please consider combining the constants.py file in the UI and the https://github.com/autogluon/autogluon-assistant/blob/main/src/autogluon/assistant/constants.py

2024-12-13 11:12 UTC, AnirudhDagar commented on src/autogluon/assistant/ui/tests/test_task_func.py
> +from constants import PRESET_MAPPING
Please use complete imports like, currently if we run the tests it fails: https://github.com/autogluon/autogluon-assistant/blob/9f7bfbc40dc251f835e11bd41639f26cc41ae42a/tests/unittests/task/test_data_loading.py#L6

2024-12-13 11:12 UTC, AnirudhDagar commented on src/autogluon/assistant/ui/tests/test_task_func.py
> +from pages.task import run_autogluon_assistant, setup_local_dataset
same as above, please make the imports complete.

2024-12-13 11:12 UTC, AnirudhDagar commented on src/autogluon/assistant/ui/tests/test_task_func.py
> +from pages.task import run_autogluon_assistant, setup_local_dataset
error that you get currently:

```
E   ModuleNotFoundError: No module named 'pages'
```

2024-12-13 11:12 UTC, AnirudhDagar commented on src/autogluon/assistant/ui/tests/test_task_widget.py
> +from constants import LLM_MAPPING, PRESET_MAPPING, PROVIDER_MAPPING, TIME_LIMIT_MAPPING
same as above

2024-12-13 11:12 UTC, AnirudhDagar commented on src/autogluon/assistant/ui/pages/task.py
@tianyuanzoe unrelated to this PR, but also needs to be fixed ASAP. These three lines are not correctly imported in the task.py file. Please commit the changes in this PR.

Please have absolute imports like `from autogluon.assistant.ui.file_uploader` and similarly for others

from file_uploader import description_file_uploader, file_uploader, save_description_file
from log_processor import messages, show_logs
from utils import (
    generate_model_file,
    generate_output_file,
    generate_output_filename,
    get_user_data_dir,
    get_user_session_id,
    save_all_files,
)

2024-12-13 11:28 UTC, AnirudhDagar commented on src/autogluon/assistant/ui/tests/test_task_func.py
> +    with patch("pages.task.generate_output_filename") as mock_gen:
Please use the full path otherwise it won't work once we move into the root tests/unittests/ui/ dir
```suggestion
    with patch("autogluon.assistant.ui.pages.task.generate_output_filename") as mock_gen:
```

2024-12-18 08:48 UTC, prateekdesai04 reviewed
Please provide a short doc string on what each test does and try to add coverage

2024-12-18 08:48 UTC, prateekdesai04 commented on src/autogluon/assistant/ui/tests/test_task_func.py
> +from constants import PRESET_MAPPING
@tianyuanzoe how did you run the tests on your local machine ?

2024-12-18 08:53 UTC, prateekdesai04 commented
@tianyuanzoe please change the CI files to add your tests, currently I am not able to see any CI runs.
You can merge the current PR along with changes in CI files and you should be able to see them on the CI runs which means you can test them, followed by which you can put follow-up PR to fix these tests as they will fail on the initial merge.

2024-12-18 20:01 UTC, tianyuanzoe commented on src/autogluon/assistant/ui/tests/test_task_func.py
> +from constants import PRESET_MAPPING
python -m pytest tests/unittests/ui
and it all passed 
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/8da6f8fe-20f9-442d-ab80-c6b425aa0ffe" />

2024-12-19 18:13 UTC, suzhoum commented
/platform_tests

2024-12-19 18:15 UTC, suzhoum commented
/platform_tests 4a9b9ee5b1c310dc78591821240e8addc0cfe7dd

2024-12-20 16:59 UTC, prateekdesai04 commented
@tianyuanzoe thanks for making the changes, have you made sure if they work in the github CI ?

2025-01-17 13:44 UTC, AnirudhDagar approved these changes
Thanks for the changes! Tested locally and also the UI tests run now in the CI.

2025-01-17 20:28 UTC, tianyuanzoe commented
Thank you Ani! @boranhan can you please help review this PR?

2025-01-28 00:56 UTC, boranhan approved these changes
LGTM

2025-01-28 04:12 UTC, tianyuanzoe commented
Thanks for the review! @AnirudhDagar @boranhan , Since I don't have write access, can you pls merge the pr, thank you!

2025-01-29 03:18 UTC, merged